name: servio
description: Letting service providers meet clients

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.28+1
  flutter_form_builder: ^3.10.1
  carousel_slider: ^2.2.1
  settings_ui: ^0.3.0
  http: ^0.12.2
  flutter_chips_input: ^1.9.0-dev.1
  google_fonts: ^1.1.0
  image_picker: ^0.6.7+6
  flutter_secure_storage: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
